### ISSUE TITLE
Trigger infinite-scroll until scrollbar appears or disabled = false

### ISSUE THREAD

**Issue by JobaDiniz** [sroze/ngInfiniteScroll#125]
Trigger `infinite-scroll="nextSlot()"` until the scrollbar appears or disabled = false.

With large windows, not all content is shown, because a scrollbar does not appear. Without scrollbar, user cannot scroll, therefore, only the first contents will be shown

**Comment by kraenhansen** [comment]
+1

**Comment by flavioreis13** [comment]
+1 Same issue. Any fix available?

**Comment by flavioreis13** [comment]
I found a little hack/fix: just add to your CSS:

```
html {
    /* ngInfiniteScroll */
    height: 101%;
}
```

**Comment by r0b-** [comment]
+1

**Comment by solomon87** [comment]
Found the solution in master as of 10/15/2015.
On line 182 the $interval() is set to run only once. Change to 0 to run indefinitely.
this:
              return $interval((function () {
                  if (immediateCheck) {
                      return handler();
                  }
              }), 0, 1);
To This:
              return $interval((function () {
                  if (immediateCheck) {
                      return handler();
                  }
              }), 0, 0);

**Comment by solomon87** [comment]
Hmm, I was able to solve the issue but it was by editing the finished JS. I was going to fork and submit a pull request but I'm not familiar enough with coffee script to edit that and build it. But here is what I did for others wanting to solve this issue:
Line 151 changes to:
```
unregisterEventListener = $rootScope.$on(scope.infiniteScrollListenForEvent, load);
```
Lines 178-182 changes to:
```
var load = function () {
    var stop = function () { $interval.cancel(l) };
    var l = $interval((function () {
        var h = handler();
        if (h === false) stop();
        return h;
    }), 0)
    return l;
}
if (immediateCheck) {
    return load();
} else {
    return $interval(function() {}, 1);
}
```

**Comment by BurakAkyildiz** [comment]
I did a little  trick like that.
On angular module define a global variable `app.value('isFirstLoad',true);`
On handler method add `$scope.isFirstLoad = false;`
On html controller scope add `{{isFirstLoad ? nextRecordPart() : ''}}`
it does the trick for no scroll bar pages on first load.

**Comment by solomon87** [comment]
Explanation as to why this was closed?

**Comment by graingert** [comment]
@solomon87 there's a [workaround](https://github.com/sroze/ngInfiniteScroll/issues/125#issuecomment-236598120)
