### ISSUE TITLE
jquery should be a bower dependency

### ISSUE THREAD

**Issue by rafriki** [sroze/ngInfiniteScroll#140]
https://github.com/wearefractal/gulp-concat does not know to put ngInfiniteScroll after jQuery because it's not listed as a dependency in project bower.json.

**Comment by graingert** [comment]
please try 1.3.0, but note that you should be using a module bundler (webpack rollup jspm) not gulp-concat

**Comment by graingert** [comment]
also bower is no longer supported, please use npm.
