### ISSUE TITLE
Infinite Scroll + Tabs

### ISSUE THREAD

**Issue by victorborrasdev** [sroze/ngInfiniteScroll#151]
Hi!

I'd like to know if it's possible to have several tabs (from angularjs UI), and an infinite scroll for each one of them. I have two different types of elements that I'd like to show separated by tabs, but right now when  I try to have them both in the same page they won't load more elements.

I'm also using deckgrid to display elements with masonry style, but I don't think that will affect.

Here's a sample of my markdown, I hope it helps to have a better idea of what I'm trying. What I'm seeing is that loadMoreThings() never gets triggered.

Thank you!

```
<tabset vertical="false" type="pills">
    <tab heading="Tab 1">
        <section ng-controller="firstController">
            <div infinite-scroll="loadMoreThings()" infinite-scroll-distance="3">  
                <div deckgrid source="mySource" cardTemplate="myTemplate" class="deckgrid"></div>
            </div>
            <div ng-show="busy" class="row-loader text-center">
                <img src="img/loader.gif" alt="loader"/>
            </div>
        </section>
    </tab>
    <tab heading="Tab 2">
        <section ng-controller="secondController">
            <div infinite-scroll="loadMoreOtherThings()" infinite-scroll-distance="3">
                <div deckgrid source="myOtherSource" cardTemplate="myOtherTemplate" class="deckgrid>
                </div>
            </div>
            <div ng-show="busy" class="row-loader text-center">
               <img src="img/loader.gif" alt="loader"/>
            </div>
        </section>
    </tab>
</tabset>
```

**Comment by davidnadeau** [comment]
There is a bug with this library where you can only have a single instance of the infinite scroll. So when you have a new instance in each tab, what actually happens is both loadMoreThings and loadMoreOtherThings get called. The result is unpredictable, sometimes it loads correctly, other times it only loads the first page.

My solution was to add a variable on the $rootScope to store what tab i'm looking at, and inside of both loadMore methods, put an if statement:

    if ($rootScope.tab !== "tab1") return;

Now it still calls all your loadmore methods, however the incorrect methods return before messing up the loading. The result is multiple infinite scroll instances working correctly.

**Comment by ankur0890** [comment]
Hi @davidnadeau  I am facing the same problem. Tried your solution but not working may be I am missing some point over here. Can you please create a fiddle of the same. That would be really useful

**Comment by miklone3** [comment]
I have the same proble, can you help me please?
the problem is when use ng-include inside uib-tabset

**Comment by graingert** [comment]
Do not use ng-include

**Comment by Navaruban** [comment]
put click event to each tabs and load list individually in one tab container


<div class="row">
        <tabset style="width:100%">
            <tab heading="All"  (select)="onSelect($event)"></tab>
            <tab heading="Draft" (select)="onSelect($event)"></tab>
            <tab heading="Published" (select)="onSelect($event)"></tab>
            <tab heading="Consumed" (select)="onSelect($event)"></tab>
        </tabset>

        <div class="container">
            <div class="row" infiniteScroll [infiniteScrollDistance]="2" [infiniteScrollThrottle]="50" (scrolled)="onScroll()" [scrollWindow]="false" style="height:500px; overflow-y: scroll;">
             
   <div *ngFor="let item of  myExamList" class="col-md-4" style="margin-top: 10px;">

                     <div class="ibox-content"  >

                            <div class="box-header with-border">
                                <a routerLink="/resouceauthoring/exam/{{item.ExamRowId}}">
                                    <h3> {{ item.Title }}</h3>
                                </a>    
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
