### ISSUE TITLE
following code is not working in my system :( why ? 

### ISSUE THREAD

**Issue by dineshlodhi69** [sroze/ngInfiniteScroll#166]
<!DOCTYPE html>
<html>

<head>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"><script>
<script type='text/javascript' src=“ngInfiniteScroll-1.0.0/build/ng-infinite-scroll.min.js”></script>
<script type='text/javascript’ src=“MyApp.js”>

</head>

<body>

<div ng-app='myApp' ng-controller='DemoController'>
  <div infinite-scroll='loadMore()' infinite-scroll-distance='2'>
    <img ng-repeat='image in images' ng-src='http://placehold.it/225x250&text={{image}}'>
  </div>
</div>

</body>
</html> 

________

(function(){
var myApp = angular.module('myApp', ['infinite-scroll']);
myApp.controller('DemoController', function($scope) {
  $scope.images = [1, 2, 3, 4, 5, 6, 7, 8];

  $scope.loadMore = function() {
    var last = $scope.images[$scope.images.length - 1];
    for(var i = 1; i <= 8; i++) {
      $scope.images.push(last + i);
    }
  };
});
})();

_____

Only blank web page displayed why ?

**Comment by sroze** [comment]
Your HTML5 doctype is not working ? What's the real problem ?

**Comment by dineshlodhi69** [comment]
I have got the solution by the way thanks ☺
I didn't include jQuery library top of angular library...
