### ISSUE TITLE
ngInfiniteScroll fires Multiple calls 

### ISSUE THREAD

**Issue by gnesher** [sroze/ngInfiniteScroll#17]
When fetching data from an external resource I will sometime see multiple calls being fired by ngInfiniteScroll.

This usually happens when there's a small delay before the data is retrieved and the user continues to scroll down.

A simple work around is to create a timeout that ensures at least 300ms (in my case) passes between calls.

Though a better solution would be to wait for the promise of the data to be resolved. I'm just not sure how to pass that data back into the service.

I can post my timeout fix but it's really straightforward.

**Comment by selvakumarpandiyan** [comment]
I tried the same, but still it fires couple of times, what is the problem

**Comment by devotis** [comment]
I tried the same, and it fixed my problem of firing a couple of times.

**Comment by graingert** [comment]
I'd recommend using 'async/cargo' instead:

```js
import cargo from 'async/cargo';

export default function DemoController($scope, $http) {
  const cargo = async.cargo(function(tasks, callback) {
      $http.jsonp(url).success(function(data) {
        $scope.data = data;
        callback();
      });
  });

  $scope.nextPage = function() {
    cargo.push({});
  };
});

DemoController.inject = ['$scope', '$http'];
```

![cargo animation](https://camo.githubusercontent.com/f4810e00e1c5f5f8addbe3e9f49064fd5d102699/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313637363837312f36383130312f38346339323036362d356632392d313165322d383134662d3964336430323431336266642e676966)

consider each orange block ng-infinite-scroll calling your function.
