### ISSUE TITLE
infinite-scroll function triggered on load without scrolling.

### ISSUE THREAD

**Issue by jfountain** [sroze/ngInfiniteScroll#172]
What happened: When the page loads, 16 items were loaded and the function I defined in infinite-scroll was triggered.

What I expected: When the page loads, I expect to see 8 items and the infinite-scroll function shouldn't fire.

This might be because of a race condition with the content loading slowly.

Easiest to reproduce with a small width browser window. Here is a plunker that is a copy of...

http://sroze.github.io/ngInfiniteScroll/demo_basic.html 

http://embed.plnkr.co/xLcW15/preview

**Comment by GuillaumeSpera** [comment]
Hello !

I had the same issue, I looked at the documentation and I found the infinite-scroll-immediate-check attribute. Since I've set it to false, the first call without scrolling doesn't occur anymore.

Could it fix your problem ?

**Comment by jfountain** [comment]
Yes, that's it.  I thought that was default to false.  I updated the plunker and it works as expected.

http://embed.plnkr.co/xLcW15/preview

Thanks!
