### ISSUE TITLE
Method not triggering when body CSS has height: 100%

### ISSUE THREAD

**Issue by lpsBetty** [sroze/ngInfiniteScroll#184]
Had anyone noticed this already or is there a workaround?

I need
````
html, body {
  height: 100%;
  overflow-x: hidden;
}
````

But when I do this, the infinite scrolling method doesn't get triggered anymore, I just use a simple ``div`` as container!

**Comment by soujanyasreenath** [comment]
I've been facing the same issue. Oh, and I'm using mobileangularui.

**Comment by lpsBetty** [comment]
:/ somebody got a solution to get it work with body height 100% ?

**Comment by lpsBetty** [comment]
@soujanyasreenath it works when you remove ``overflow-x: hidden`` !
I just add another div#wrapper directly after body and used it like this:
````
html, body {
  height: 100%;
}
#wrapper {
  overflow-x: hidden;
}
````

**Comment by lpsBetty** [comment]
@soujanyasreenath  sorry .. this only works in Chrome, not Firefox :/

**Comment by bahoo** [comment]
I ran into similar troubles and resolved it by specifying which element will actually be doing the scrolling; a wrapper `<div>` in our case:

    <div infinite-scroll-container="'.page-wrapper'" ... >

Undocumented, but very handy. Hope this helps someone else!

**Comment by lpsBetty** [comment]
@bahoo you are my hero! :+1:   
I fixed the problem with
````
infinite-scroll-container="'body'"
````

**Comment by shawn-simon** [comment]
I love you guys

**Comment by tjay27** [comment]
@bettysteger 
I was dealing with a similar problem and removing this overflow-hidden worked like a charm. absolute saviour! thankyou
