### ISSUE TITLE
jQuery listed as a dependency, but ngInfiniteScroll is working without it...

### ISSUE THREAD

**Issue by shawn-simon** [sroze/ngInfiniteScroll#185]
No idea why, but my site doesn't include jQuery and it's working. Perhaps angular has added support on element enough for this to work?

**Comment by shivenigma** [comment]
angular is using jquery mobile internally, so this maybe working. I'm not sure anyway

**Comment by 12kb** [comment]
Doesn't work without jquery for me.

Angular uses jqlite - own lightweight implementation of jquery. It's not enough for infinite-scroll.

**Comment by mmmeff** [comment]
Honestly, why does this need jQuery? What could possibly be worth the enormity of $?

**Comment by shivenigma** [comment]
It didn't worked for me too without jquery @shawn-simon .
