### ISSUE TITLE
bower package name throws error

### ISSUE THREAD

**Issue by clamstew** [sroze/ngInfiniteScroll#192]
I got a bower install error that said `The name contains upper case letters`; this seems to block it from installing through bower.  The [bower docs](http://bower.io/docs/creating-packages/#register) mention: 

> The package name must adhere to the [bower.json spec](https://github.com/bower/bower.json-spec#name).

bower.json spec goes on to say that:

* Should be slug style for simplicity, consistency and compatibility. Example: unicorn-cake
* **Lowercase, a-z**, can contain digits, 0-9, can contain dash or dot but not start/end with them.

----
I assume this means that the [name in bower.json](https://github.com/sroze/ngInfiniteScroll/blob/master/bower.json#L2) should be all lower case something like **"ng-infinite-scroll"**.

**Comment by graingert** [comment]
please try "npm install --save ng-infinite-scroll"

**Comment by graingert** [comment]
bower is no longer supported

**Comment by thienedits** [comment]
fyi there's another package with that name
https://github.com/ash-developer/ng-infinite-scroll

**Comment by graingert** [comment]
@thienedits try`yarn add ng-infinite-scroll`
