### ISSUE TITLE
loads all pages at once

### ISSUE THREAD

**Issue by mpmlj** [sroze/ngInfiniteScroll#197]
Hi,

I have the following issue: ngInfiniteScroll loads all pages in sequence, one by one until there's no data left in API and will display all data at once.

Whole setup is very close to their demo: http://sroze.github.io/ngInfiniteScroll/demo_async.html

1. Material Design, AngularJS 1.3.17
2. I'm using it inside a view.
3. Div with ng-repeat has class="col-sm-12". If I remove this class or set style="float:none" the behavior changes: shows only one set of data as expected, but when scrolled to the bottom, it is not requesting for the next set to load :/

Any help is highly appreciated!

**Comment by pbassut** [comment]
+1

**Comment by pbassut** [comment]
bump

**Comment by pbassut** [comment]
Look at #90

**Comment by oharlem** [comment]
@pbassut 
Thank you for the link, however I had the doctype ^ from the very start. Not the cause in my case :/

**Comment by EMProduct** [comment]
+1 , have you solved it ??

**Comment by mpmlj** [comment]
@EMProduct 
I've found a fork that seems to be working: https://github.com/oxenti/ngOxenti-infinite-scroll
However, have not tested extensively yet.

**Comment by EMProduct** [comment]
@mpmlj  I'm sorry I'm new here , I didn't know how to install it , I tried  "bower install ngOxenti-infinite-scroll" , and tried replacing the ngInfiniteScroll folder with ngOxenti-infinite-scroll-master and changing the included script with no luck , all the data just keep loading at the beginning without even touching the scroll , can you help?

**Comment by mpmlj** [comment]
@EMProduct 
Check the following please:
1. I'm using "ngOxenti-infinite-scroll": "~1.2.3" in my bower.json
2. They've changed the module name, so need to use "angularInfiniteScroll" now instead of "infinite-scroll"
3. Not sure if 100% related but you may beed to use  <div style='clear: both;'></div> in the end of the div with ng-repeat.

Hope this helps,
D.

**Comment by laurensnl** [comment]
In my case it only loads all items on iOS (both Chrome & Safari). On Mac, it works as expected.

Any solutions to this yet?

**Comment by graingert** [comment]
please try 1.3.0
