### ISSUE TITLE
Does ng-infinite-scroll handle multiple routes & view changes?

### ISSUE THREAD

**Issue by viking2917** [sroze/ngInfiniteScroll#198]
I have a reasonably complicated app with multiple views. I'm using ng-infinite-scroll together with angular-masonry-directive for an infinite scrolling masonry panel. If I hit a url / route that invokes infinite scroll, it works fine the first time the view is loaded. If I change to another view, then come back to the first view, the infinite-scroll function/handler does not get triggered. If I reload the page, it does get triggered.

I noticed this line: 
        `windowElement = angular.element($window);`
is called the first time the page is loaded, but the value of windowElement is never reset, and it appears to me that after a route change, the $window is different. If I add that line again inside the handler function like so:

        handler = function() {
           var containerBottom, containerTopOffset, elementBottom, remaining, shouldScroll;
           windowElement = angular.element($window);

the problem appears to go away. 

Am I doing something wrong, or is there an issue with ng-infinite-scroll and view changes.

**Comment by viking2917** [comment]
actually, I retract the statement that the change I made resolves the issue. Still having it. closing the issue until I can figure more out.

**Comment by viking2917** [comment]
I discovered the source of the problem (my fault). In case anyone else runs into a similar issue:  I was using the infinite-scroll-container with a class selector. Each of my views shares a class name. Conceptually, only one can occur at a time, but during state change there can be two of them, and this was confusing ng-infinite-select as it was picking the "wrong" (dying) one. Somewhat related to this issue: 

https://github.com/sroze/ngInfiniteScroll/issues/178.

Putting a unique id on each infinite-scrollable element, and using that as the ng-infinite-scroll-container, cured the problem.

**Comment by mukulgupta2507** [comment]
Hi,

I'm also facing a similar issue where I need to use infinite-scroll-container to specifiy a dynamic classname/id as I have multiple widgets on one single page each of which can have infinite scrollable content. Since I'm using angularjs and jade tempate engine, I'm wondering how can I give a dynamic id/class name inside this property. I have opened one thread on SO: http://stackoverflow.com/questions/33190595/using-infinite-scroll-in-angularjs-and-jade Can anyone please help me how can I achive this ?

Thanks

**Comment by shahakshay94** [comment]
I am facing the same issue. I have multiple views and when the page is loaded for the first time, scrolling works fine but when I switch between views and again come back to the same view, scrolling stops working. If I reload the page, scroll works fine again. Any help is appreciated.
