### ISSUE TITLE
TypeError: n.height is not a function

### ISSUE THREAD

**Issue by geraldvillorente** [sroze/ngInfiniteScroll#200]
Having trouble in implementing infinite scroll with Angular 1.4.3. Below is the console errors.
```
TypeError: n.height is not a function                   angular.js:12330 
Uncaught TypeError: n.height is not a function   ng-infinite-scroll.min.js:2 
```

**Comment by kalyansriram** [comment]
Check whether you have included jquery into your site

**Comment by geraldvillorente** [comment]
@kalyansriram thanks. Putting jQuery before AngularJS solve the issue.
