### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by rcollette** [sroze/ngInfiniteScroll#204]
I would submit a pull but documentation is not part of this repository.

Missing documentation appears to be:

* **infinite-scroll-container** - An expression that results in an HTMLElement object, an array whose first element is evaluated using angular.element(),or  a string which is used as the parameter to document.querySelector().  The selector is similar to jQuery selectors but should evaluate to a single element.  Remember to use single quotes around string constants.  See http://plnkr.co/edit/m2HUv9xKKpebSIjMfsxT?p=preview for an example.
* **infinite-scroll-use-document-bottom** - An expression that evaluates to boolean.  If true, the distance to the bottom of the document is used in conjunction with infinite-scroll-distance rather than the scroll distance to the bottom of the element on which the ngInfiniteScroll directive is placed.
* **infinite-scroll-parent** - If this attribute exists, the scroll container that is tracked is the parent element of the element on which the ngInfiniteScroll directive is placed.  See http://plnkr.co/edit/dkDsBA57jT0VQWBPyIEy?p=preview

**Comment by pbassut** [comment]
:+1: Thanks. This helped me.

**Comment by plong0** [comment]
:+1: me too.  thanks @rcollette  :)

**Comment by weisk** [comment]
Thank you for this... it seems the author is long time gone ..?

**Comment by sroze** [comment]
No, it just needs a major refactoring coming soon :)

**Comment by weisk** [comment]
oh great dude!

**Comment by rewiredpictures** [comment]
:+1: thanks @rcollette

**Comment by VictorCoding** [comment]
you rock! :beer:

**Comment by aseckel** [comment]
:+1:

**Comment by tekdungtralala** [comment]
:+1:

**Comment by santiq** [comment]
👍

**Comment by rcollette** [comment]
PR created.
https://github.com/sroze/ngInfiniteScroll/pull/339
