### ISSUE TITLE
Event being triggered continuously 

### ISSUE THREAD

**Issue by pbassut** [sroze/ngInfiniteScroll#212]
I don't know why the event is being triggered continuously once it reaches the bottom once.
This looks like a really simple issue that I've been struggling with for hours now.
I had the same problem when using on the whole page(now i'm using it in a notification window). But after adding the doctype, the problem went away.
Now, even with a doctype it's not working.

Any ideas?

**Comment by pbassut** [comment]
bump...

Does it have support for small windows like a notification, for example? I'm getting the handler trigger continuously.

**Comment by sal-gb** [comment]
This directive scroll infinitely (it's in the name).
If you're fetching from a finite source you need to tell it to stop checking for the scrolling.

You need to put a check on your 'load more' function to see when it needs to stop.
Add infinite-scroll-disabled='scrollingdisabled' to your html tag, and whenever you are done putting in new elements do a $scope.scrollingdisabled=true; on whatever controller you are using this from.

**Comment by pbassut** [comment]
I think you didn't understand it.
Once it reaches the bottom once, it fires MULTIPLE times and indefinitely. It should fire once(or a couple would be acceptable). 
That shouldn't happen as I see.

Note that I'm using it already on one element and it works fine. I mentioned that in the issue. 
The problem now is that I moved to a "notification popup". Like facebook's.

**Comment by litera** [comment]
@pbassut No you didn't understand. When you reach the bottom (the first time) you should disable it and it won't fire again.

**Comment by YuvPrime** [comment]
I'm facing the same issue. LoadMore() function fires even when we on top or middle. Any solution?

**Comment by pbassut** [comment]
As @YuvPrime pointed out. It fires even when not in the bottom. Which I'm not sure it should.
Also, if I have to disable when it's not on the bottom, I don't really see the benefit of using this library.

If that is not the intended behaviour this library provides, I'll close this issue and move on.

**Comment by langdonx** [comment]
@pbassut As two others have said, you can use `infinite-scroll-disabled` to stop the even from triggering once you've gotten all the data you can get.

It's an **infinte** scroll directive, you need to use the `infinite-scroll-disabled` attribute to make it finite.

**Comment by pbassut** [comment]
Right. Maybe the title is bad. 
What I mean is
