### ISSUE TITLE
what ngInfiniteScroll will bring me?

### ISSUE THREAD

**Issue by wzshuang** [sroze/ngInfiniteScroll#213]
I write a directive named 'scroll', it broadcast an event when the body element scrolled to the bottom, then my controller capture the event and request data from server, then I add the data to the model, the view changed automatically. everything works just fine for me.
My question is, what ngInfiniteScroll will bring me? I read the document and doesn't find something special, thanks.

**Comment by smart987** [comment]
please put your directive code here.
