### ISSUE TITLE
Publish 1.2.1 to npm

### ISSUE THREAD

**Issue by patlux** [sroze/ngInfiniteScroll#215]
:+1:

**Comment by bialikover** [comment]
:+1:  on this should be promoted to npm, faced some issues today because the infinite-scroll-container attribute does not works in 1.2.0

**Comment by graingert** [comment]
:+1:

**Comment by graingert** [comment]
@sroze it's been quite a while since the last release on npm.

**Comment by stevermeister** [comment]
:+1:

**Comment by sroze** [comment]
Done!

**Comment by graingert** [comment]
@sroze nice, thanks!
