### ISSUE TITLE
Question: Why do you need jQuery?

### ISSUE THREAD

**Issue by davidloiret** [sroze/ngInfiniteScroll#222]
Why do you need jQuery?

**Comment by se-panfilov** [comment]
Is somebody know forks without jquery dependency? (btw, jquery is a most disadvantage for use this lib)

**Comment by deividfortuna** [comment]
I don't want include jquery only for use this lib :-1:

**Comment by graingert** [comment]
@davidloiret works without jQuery.

**Comment by gamebox** [comment]
@graingert Are you sure?  From the homepage:

> Include the ngInfiniteScroll JavaScript source script tag on your page, after the script tags for jQuery and AngularJS (ngInfiniteScroll requires the use of jQuery).

If this is the case, maybe I should submit an issue to fix the copy here?

**Comment by graingert** [comment]
@gamebox yeah, can you send a pr to the gh-pages branch please?

**Comment by gamebox** [comment]
Sure thing, will do when I get home tonight
