### ISSUE TITLE
Seriouse Performance Issue with New $interval added 1.2.2

### ISSUE THREAD

**Issue by onemenny** [sroze/ngInfiniteScroll#235]
@sergiovilar Commited a change https://github.com/sroze/ngInfiniteScroll/commit/68c505d131e14b6e4997ab83dc675d67209634ad

**This causes a serious performance degregation**  since the count was removed from the $interval call - it causes a digest loop to run  indefinitely which will slow down to the ground every application 

The new version 1.2.2 is just not usable and should revert to 1.2.0

**Comment by sroze** [comment]
Can't it be the same as #186 ?

**Comment by onemenny** [comment]
No, it does not matter if reach the end, It is related that the $interval method works  indefinitely causing an endless digest cycles

**Comment by sergiovilar** [comment]
Hey, sorry about that. There's any suggestion to fix the issue?

**Comment by onemenny** [comment]
Sorry, I don't know what this fix meant to do, I have no problems with 1.2.0. One can always use the disable option

**Comment by morgoth** [comment]
I confirm the issue. Angular tests in our app started to fail with timeout. Reverting to 1.2.1

**Comment by pudo** [comment]
Confirmed here, too. Showstopper.

**Comment by pierrebeitz** [comment]
+1

**Comment by dirkgroenen** [comment]
Same issues over here, looks like the `$interval` is running each ms. Didn't check why the interval needs to run, but it might be worthy to check if we can't change it to the browser's native `setInterval` so we don't call a digest cycle each millisecond.

**Comment by dirkgroenen** [comment]
@sergiovilar before making any suggestions, what was the reason for adding the interval and making it run the digest cycle?

**Comment by timburnham73** [comment]
+1 I have the same problem. It broke our protractor tests in chrome only. Firefox worked which is strange.

**Comment by scottmollon-invicara** [comment]
+1 breaking all our protractor tests!

**Comment by hobbysoldat** [comment]
+1

**Comment by sroze** [comment]
@sergiovilar could you PR a fix please?

**Comment by jmblck** [comment]
+1 I have this problem with 1.2.2, not in 1.2.0.

**Comment by feimosi** [comment]
+1, also happens on 1.2.2

**Comment by pelizza** [comment]
+1, happens on 1.2.2 but not on 1.2.1.

**Comment by belfz** [comment]
+1, although for me it happens on 1.2.1.

**Comment by onemenny** [comment]
@sroze @sergiovilar 
Can someone please revert this commit, this is starting to be embarrassing.

**Comment by janhartigan** [comment]
@onemenny just revert to an old release on your app until this is fixed.

**Comment by david-gang** [comment]
In my opinion it should be at least mentioned in the readme just to use 1.2.0

**Comment by onemenny** [comment]
@janhartigan That's exactly what I did, but still, this is kind of ridicules that the main version is not functioning for that long. @david-gang is right

**Comment by scanferla** [comment]
+1 

Took me and my team quite some time to figure this one out 😢

**Comment by sroze** [comment]
True, I'll fix that today.

**Comment by stephenycchang** [comment]
I'm having an issue where there are over 200 digests per second just from implementing this plugin in a sample barebone project. Think it's related as well.

**Comment by miguelolmo** [comment]
+1 reverting to 1.2.1 fixed it for me

**Comment by belfz** [comment]
What's the status of that? Version 1.2.0 doesn't work for me, and version 1.2.1 (or 1.2.2) was not fixed yet.

**Comment by woutrbe** [comment]
Reverting to 1.2.1 or 1.2.0 didn't work for me. Is there any update on this?

**Comment by belfz** [comment]
There was a [pull request](https://github.com/sroze/ngInfiniteScroll/pull/270) merged and closed recently, but no new version released yet. @sroze could you release at least patch version? Thank you in advance.

**Comment by peder** [comment]
Some users report that this is not working in 1.2.1 either. Can anyone confirm that the Pull Request changes fix the issue? Also, any update on publishing 1.2.3?

**Comment by graingert** [comment]
NPM "ng-infinite-scroll": "1.2.0", is the only one that works for me.

**Comment by eXaminator** [comment]
We are also experiencing this, more than 3 month after this serious bug was reported it is still not resolved. Please release a new version with a fix for this (as someone stated it seems to be merged) and publish it to NPM (it seems the last version on NPM is 1.2.1 while github already has 1.2.2).

**Comment by graingert** [comment]
@onemenny @eXaminator please try 1.3.0

**Comment by mephinet** [comment]
Tested 1.3.0 - $interval has it's 3rd parameter again, performance is back to normal. Thanks, @graingert for fixing this!
