### ISSUE TITLE
Scroll get's in an endless loop 

### ISSUE THREAD

**Issue by cmodijk** [sroze/ngInfiniteScroll#242]
Sinds the latest version (1.2.2) we are getting in an infinite loop when we move from one pagina to another page. We have multiple pages which uses angular ui router and we use ngInfiniteScroll for infinite scrolling. But if i install the 1.2.2 version and i go from one page to another which are the same controller with different params the `infinite-scroll` method get's called in an endless loop. When i switch back to the 1.2.1 version it al works fine. 

![ezgif-579824097](https://cloud.githubusercontent.com/assets/771041/12822613/248e6986-cb69-11e5-8743-d0e5983f16c2.gif)

**Comment by jerryc-nguyen** [comment]
yes, same as me. Also for 1.2.1. Please fix it.

**Comment by jasonbodily** [comment]
I'm experience this same problem. What can we do to help?

**Comment by sroze** [comment]
This is a duplicated of #235.
