### ISSUE TITLE
A Port to Angular 2 is available

### ISSUE THREAD

**Issue by orizens** [sroze/ngInfiniteScroll#243]
Hi. 
I'm using this directive and haven't found an angular 2 implementation. So, I forked the repo and ported some of it to angular 2. 
https://www.npmjs.com/package/angular2-infinite-scroll 
Perhaps it will be worthwhile for others to include a link to angular 2 version in the READMe.md. 

Cheers.

**Comment by sphaso** [comment]
There's a PR with my translation to Angular2 (https://github.com/sroze/ngInfiniteScroll/pull/238). Perhaps you'd like to collaborate on it?

**Comment by orizens** [comment]
Looks interesting.
I took a different approach by isolating the logics to an external class, agnostic to angular.
still, I haven't implemented all.

**Comment by sphaso** [comment]
I translated almost verbatim, you can see what I'm missing from the PR. Next I'd like to make it work with jenkins and the protractor tests, but I know nothing about both :)

**Comment by graingert** [comment]
continue discussion on https://github.com/sroze/ngInfiniteScroll/pull/251
