### ISSUE TITLE
Publish 1.2.2 to npm

### ISSUE THREAD

**Issue by graingert** [sroze/ngInfiniteScroll#244]
@sroze looks like 1.2.2 got released for bower but not NPM

**Comment by sroze** [comment]
This version introduced serious problems (see #235), will do for 1.2.3 only.

**Comment by rarkins** [comment]
Should we revert to 1.2.1 in the meantime?

**Comment by graingert** [comment]
@sroze is this project unmaintained?

**Comment by sroze** [comment]
I'm looking for other maintainers to help me!

**Comment by graingert** [comment]
@sroze can you please release a new version 1.30 maybe that is the verified working version? On both npm and bower.

**Comment by graingert** [comment]
Because 1.21 and 1.20 are different on bower and npm, and 1.22 is not on npm.

**Comment by rarkins** [comment]
I created https://github.com/sroze/ngInfiniteScroll/issues/292
