### ISSUE TITLE
¡Ayuda!

### ISSUE THREAD

**Issue by adrianojosue** [sroze/ngInfiniteScroll#247]
Alguien me haría el favor de explicarme cómo puedo implementar ngInfiniteScroll con un archivo local .json ? De antemano ¡Muchas gracias!

**Comment by cyberkatze** [comment]
english please

**Comment by AdrianoJosue** [comment]
I could help me to implement ngInfiniteScroll with a local file .json

**Comment by BenevidesLecontes** [comment]
Take a look in my code, I already did it with json file. 

 $scope.IMAGE_LOCATION = '../images/portfolio/';
    // Retrieve and set data
    DataSource.get('/scripts/JSonFiles/images.json', function (data) {
      $scope.galleryData = data.slice(0, 4);
      $scope.AllgalleryData = data;
      $scope.selected = data[0];
    });
    $scope.loadMore = function () {
      if ($scope.galleryData === undefined || $scope.AllgalleryData === undefined) {
        return;
      }
      var last = $scope.galleryData.length - 1;
      for (var i = 1; i <= 4; i++) {
        if ($scope.galleryData.length >= $scope.AllgalleryData.length) {
          break;
        }
        $scope.galleryData.push($scope.AllgalleryData[last + i]);
      }
    };

**Comment by AdrianoJosue** [comment]
@BenevidesLecontes It does not work me :(

JavaScript:

.controller('ItemListCtrl', ['$scope', '$http', 'DataSource', function($scope, $http, DataSource){
      DataSource.get('json/news.json', function(data){
        $scope.itemData = data.slice(0,6);
        $scope.itemsData = data;
        $scope.selected = data[0];
      });
      $scope.loadMore = function(){
        if($scope.itemData === undefined || $scope.itemsData === undefined){
          return;
        } var last = $scope.itemData.length - 1;
          for(var i=1; i<=6; i++){
            if($scope.itemData.length >= $scope.itemsData.length){
              break;
            } $scope.itemData.push($scope.itemsData[last + i]);
          }
      };
  }]);

.factory('DataSource', ['$http', function($http){
    return{
      get: function(fileName, callback){
        $http.get(fileName).then(function(response){
          callback(response.data);
        }, function(){
          console.log('error');
        });
      }
    };
  }]);

HTML:

ul  infinite-scroll="loadMore()" infinite-scroll-distance="1"
li   ng-repeat="item in itemData | orderBy:'-id' | filter:search as results"

**Comment by BenevidesLecontes** [comment]
What is the errors?

**Comment by AdrianoJosue** [comment]
¡and I could implement it, thank you very much, I appreciate it! :)
But now I have a problem, my (Filter: search as results) no longer works, maybe you can help me to fix this. My Filter is simple:
`input type="search" ng-model="search.title"
li ng-repeat="item in itemData | orderBy:orderProp | filter:search as results"
`

**Comment by BenevidesLecontes** [comment]
@AdrianoJosue I didn't understand what you trying to filter. But here my filter on the project that i used infinitescroll and maybe you could do like i did:
ng-repeat="image in galleryData | filter:x as results track by $index"

**Comment by AdrianoJosue** [comment]
@BenevidesLecontes What role does "track by $index" ?

**Comment by jesusr** [comment]
@AdrianoJosue track by $index is a generic filter usually used at the ng-repeat directive. It sets a $index, a variable like the "i" var at a for loop.

See more at https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by AdrianoJosue** [comment]
Disculpa @jesusr puedes ayudarme ? Publique mi problema en stackoverflow.
[http://es.stackoverflow.com/questions/6699/error-implementando-nginfinitescroll-con-un-input-type-search-y-el-viewport-del](url)

**Comment by BenevidesLecontes** [comment]
@AdrianoJosue you're confusing yourself. The way your code is implemented, it load only 6 item because this line $scope.itemData=data.slice(0,6);
And when you scroll and hit the distance that you set on the infiniteScroll it load more images. That's why in your case, when you resize the browser to small size it load all the items that you have on .json file.

**Comment by adrianojosue** [comment]
Hi @BenevidesLecontes ¿How I can change the code to seek multiple json files separated by id?
