### ISSUE TITLE
scroll function is being called infinitely

### ISSUE THREAD

**Issue by gustavolira** [sroze/ngInfiniteScroll#250]
Hi,
I just did:
`<tbody class="inner-dashboard" infinite-scroll="scrollMyRecruitmentsToNextPage()" infinite-scroll-distance="0">`

My scroll function is being called infinitely.

If I resize my browser windows to be smaller, the scroll function stop to be called.

I'm using a 24 inches full hd monitor

**Comment by cyberkatze** [comment]
+1

**Comment by cyberkatze** [comment]
fixed with this code

```js
    vm.loadMoreBigData = function () {
        vm.chartSeriesTablePos += vm.chartSeriesTableCurPos;

        var c = vm.chartSeriesTableCurPos,
            n = vm.chartSeriesTablePos,
            tmp = null,
            sLen = vm.chartSeries.length;

        for (var i = 0; i < sLen; i++) {
            tmp = JSON.parse(JSON.stringify(vm.chartSeries[i].bigdata));
            tmp = tmp.slice(c, c + n);
            vm.chartSeriesTable[i].bigdata = vm.chartSeriesTable[i].bigdata.concat(tmp);
        }
        tmp = null;
    };
```

**Comment by silentHoo** [comment]
@cyberkatze Could you please explain in short why this works?

**Comment by cyberkatze** [comment]
@silentHoo 

this worked on me because data exist for infinity-chartSeriesTable-Object (or done with update/$apply()). Don't know exactly, but now work. My problem was that the infinity-collection had no data from chartSeries-collection. If I don't do this, I got unstoppable infinity event in console.log and can not work. Change windows size don't help me as @gustavolira wrote.

**Comment by sphaso** [comment]
@cyberkatze @gustavolira 
- would you be able to create a plnkr reproducing this issue?
- have you tried using ```infinite-scroll-immediate-check="false"```?

**Comment by cyberkatze** [comment]
@sphaso
I'm sorry, but I can not send my full code in public for testing.

**Comment by gustavolira** [comment]
I will try create a plunker for this, but will be difficult to reproduce because with another developers of my team they don't have this problem because the resolution of their notebooks

**Comment by gustavolira** [comment]
infinite-scroll-immediate-check="false" worked like a charm! 
Thank you
