### ISSUE TITLE
Use ngInfiniteScroll with Cordova and iOS

### ISSUE THREAD

**Issue by AnfiGroup** [sroze/ngInfiniteScroll#253]
It is posible to use ngInfiniteScroll with Cordova and iOS?

**Comment by sroze** [comment]
It is :)

**Comment by AnfiGroup** [comment]
;) Thank you... but how? I tried and it is not detected the scroll event. It is working perfect in the web browser but I can't use it in the iOS version.

**Comment by timashev** [comment]
+1
I'm having the same problem. It seems that this issue is almost 2 years old: #104

**Comment by cyberkatze** [comment]
work good with angular and pure Cordova - without Ionic!!!
