### ISSUE TITLE
Update nuget package with 1.2.2

### ISSUE THREAD

**Issue by scripni** [sroze/ngInfiniteScroll#254]
The [nuget repository](https://www.nuget.org/packages/ng-infinite-scroll/) only contains version 1.0.0. Could we have the latest version (1.2.2 as of now) published there?

**Comment by mchambaud** [comment]
+1 to this

**Comment by graingert** [comment]
nuget is no longer supported. Please install from npm.

**Comment by scripni** [comment]
Unfortunately that's not possible for us right now, our continuous integration system doesn't support npm yet. I'm happy to share ownership of the nuget package, I can help keeping it up to date.

**Comment by graingert** [comment]
Which provider do you use?
