### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by BenevidesLecontes** [sroze/ngInfiniteScroll#257]
Bower issues, it says on dependencies "~1.2.1", but download 1.2.0.

**Comment by mikeymco** [comment]
Unfortunate bump. It looks like somehow Bower is serving up 1.2.0 and NPM is stuck on 1.2.1.

@sroze if I can help by filing an issue over at the Bower component registry repo, just say the word.

**Comment by graingert** [comment]
please try 1.3.0 (the last version supporting bower, please switch to npm)
