### ISSUE TITLE
checkInterval causes infinite $digest loop w/ easy repro

### ISSUE THREAD

**Issue by dshefchik** [sroze/ngInfiniteScroll#261]
I noticed this happening in my production app, figured I should let you know. Here's the Plunkr: https://plnkr.co/edit/M3D50zy0kq1hB7dUTEa6?p=preview

Notice there are 35 items added to the list, but the $digest loop throws an exception after 350+ in a fraction of a second, calling a filter to demonstrate.

**Comment by kfarst** [comment]
Hey @dshefchik I don't think this actually has to do with `ngInfiniteScroll`, if you remove `infinite-scroll="loadMore()"` you'll see that you still get the error, I think it's the way the rest of your code is structured.

**Comment by TheNemus** [comment]
I noticed the same thing just after update from 1.2.1 to 1.2.2:

ngInfiniteScroll.js checkIntervals cause an infinite digest loop.  As I came back to te 1.2.1 everything goes fine

**Comment by dshefchik** [comment]
This bug is already covered by #235
I'm going to close it and submit a PR.
