### ISSUE TITLE
Including the module is causing infinite page reloads.

### ISSUE THREAD

**Issue by scarrick68** [sroze/ngInfiniteScroll#268]
I included the path to the script, I included the the module in my app but I did not include the directive anywhere in the page yet and the page just keeps reloading. 3 errors flash in my console, but the page reloads too fast to read them and I'm not sure how to pause the page. If I remove the module from my apps dependencies, the infinite reloading doesn't happen.

The path to my script, after using bower install, is:
scripts/bower_components/ngInfiniteScroll/build/ng-infinite-scroll.min.js

**Comment by shaynemclevy** [comment]
Use version 1.2.1, 1.2.2 is busted.

**Comment by thiago-negri** [comment]
This was causing my protractor tests to timeout while waiting for synchronization.

Downgrading to 1.2.1 solved it.

**Comment by graingert** [comment]
please try 1.3.0
