### ISSUE TITLE
virtual repeat 

### ISSUE THREAD

**Issue by david-gang** [sroze/ngInfiniteScroll#269]
Hi,

Would it be possible to use nginfinitescroll with [virtual repeat] (https://material.angularjs.org/latest/demo/virtualRepeat)?

This would be great for big lists.

The major selling point would be, if the item size could be variable, which is not possible with the material virtual repeat.

Thanks,
David

**Comment by DmitryEfimenko** [comment]
+1

**Comment by graingert** [comment]
https://material.angularjs.org/latest/demo/virtualRepeat actually supports infinite scroll.

**Comment by david-gang** [comment]
Hi @graingert .
I know, but it supports just lists  with a fixed item height.
I have a list where the item size is variable, What i need is a list which does not grow all the time.
I need something on a page basis, meaning that if i scroll down i get the next page and if i scroll up i get the last page.
It would be better if there would be something more fine grained, but i suspect that for this i will need to give a fixed item size.

Thanks,
David

**Comment by graingert** [comment]
@david-gang that sounds like something you'll need to hand roll so it integrates with the URL router and the back button
