### ISSUE TITLE
Not working with angularjs 1.x

### ISSUE THREAD

**Issue by lolaswift** [sroze/ngInfiniteScroll#297]
Is this only for angularjs 2.x?

**Comment by graingert** [comment]
hey @lolaswift this is currently tested on angular "1.2.29", "1.3.20", "1.4.12", "1.5.7"

Please try to write complete, reproducible, specific bug reports. You must include a clear, concise description of the problem, and a set of instructions for replicating it. Add as much debug information as you can: code snippets, test cases, exception backtraces, screenshots, etc. A nice small test case is the best way to report a bug, as it gives us an easy way to confirm the bug quickly.

**Comment by lolaswift** [comment]
hi Graingert. my apology. Just a stupid mistake. I used the wrong version. following the instruction of https://sroze.github.io/ngInfiniteScroll/index.html# and it's working.

**Comment by graingert** [comment]
@lolaswift those docs are a bit outdated, it's best to use:

```shell
npm install ng-infinite-scroll
```

**Comment by graingert** [comment]
instructions:

https://github.com/sroze/ngInfiniteScroll/blob/master/README.md#getting-started

**Comment by lolaswift** [comment]
Hi Thomas, thank you so much for your help. Followed the old doc, I got the 1.0.0 version.
 I am new to web development. My apology if my question is a bit silly.
Since I use bower for my project. I run:
bower install --save ngInfiniteScroll#1.3.0
Is it also OK?

**Comment by graingert** [comment]
if you have bower installed you also have node installed.

It's best to run "npm install --save ng-infinite-scroll" then instead of

```html
<script src="./bower_components/ng-inifinite-scroll/build/ng-infinite-scroll.js"></script>
```

use

```html
<script src="./node_modules/ng-inifinite-scroll/build/ng-infinite-scroll.js"></script>
```

**Comment by graingert** [comment]
@lolaswift you might also be better off with https://material.angularjs.org/latest/demo/virtualRepeat

**Comment by lolaswift** [comment]
Hi Thomas, I actually use material design.  If I use virtualRepeat infinite scroll, do I still need to install the node_module by running npm install --save ng-infinite-scroll? Or material design has already installed it as a dependency?

**Comment by graingert** [comment]
@lolaswift "material design" is an abstract concept, do you mean angular-material?

If you want to use virtualRepeat from angular-material you don't need ng-infinite-scroll so it's:
```
npm install --save angular-material
```
```
<script src="path/to/node_modules/angular-material/angular-material.js"></script>
```

**Comment by lolaswift** [comment]
Indeed, I meant angular-material. When I can use virtual repeat, I should use the virtual repeat infinite scroll for better dom performance. In case I need to use the regular ng-repeat( since virtual repeat can't replace ng-repeat completely), I should use ng-infinite-scroll.js. Do I understand it properly this time? 

The reason why I want to use the infinite scroll is because currently I am using md-data-table but I don't like the pagination and also because I use AWS dynamodb as my backend database, doing traditional pagination isn't a good choice. On my ionic app, I already use the ionic infinite scroll and it's awesome. And thanks to you all, we can have infinite scroll for our web apps as well.

**Comment by graingert** [comment]
you should be able to use virtual repeat md-virtual-repeat wherever you used ng-repeat, you just might need to create a  mdVirtualRepeatModel wrapper.

**Comment by lolaswift** [comment]
Hi Thomas, now I understand 👍 . Can't thank you enough for being so patient and so helpful. You guys are making our world more awesome! Thank you!!

**Comment by lolaswift** [comment]
@graingert. Hi Thomas, sorry that I keep commenting on a closed issue. I just came back to say thank you and the team for your awesome work on ngInfiniteScroll. I got it work on my project and I am so happy. ngInfiniteScroll works almost out of box and offers clear documentation and easier controls like:
        infinite-scroll="vm.onLoadMore()" 
	infinite-scroll-disabled="!vm.moreDataCanBeLoaded() || vm.busyLoadingData" 
	infinite-scroll-container="'#container'"
	infinite-scroll-immediate-check="false"
	infinite-scroll-distance="1">
Even a newbie like me could get it work. You guys are awesome!!
virtual repeat has better performance but it's lacking of documentation. I also got it work but it got triggered multiple times and I haven't figure out how to control its behavior like how we can do it when using ngInfiniteScroll. 
thx again and please keep up the GREAT work!
--lola

**Comment by zygmcc** [comment]
same problem , the lastest version of ngInfiniteScroll works not well with angular 1.4.6
so, I found ngInfiniteScroll v1.0.0 which @lolaswift mentioned in https://raw.githubusercontent.com/BinaryMuse/ngInfiniteScroll/1.0.0/build/ng-infinite-scroll.min.js
,finally solved that problem ;  :)

**Comment by zygmcc** [comment]
finally ,I use ngInfiniteScroll-1.2.2 , seems works very well with angular 1.4.6

**Comment by lolaswift** [comment]
@zygmcc Hi zygmcc, glad that you found your solution too. I wish Angular could have something similar to ionic infinite scroll :-)
