### ISSUE TITLE
Module cannot be found

### ISSUE THREAD

**Issue by harrison0723** [sroze/ngInfiniteScroll#313]
I have npm installed with `npm install --save ng-infinite-scroll`

Then I added it as dependency 
`
window.app = angular.module('MyApp', ['auth', 'infinite-scroll', 'ui.router', 'ngAnimate']);
`

Yet when I go to localhost, console returns:
```
angular.js:4640 Uncaught Error: [$injector:modulerr] Failed to instantiate module MyApp due to:
Error: [$injector:modulerr] Failed to instantiate module infinite-scroll due to:
Error: [$injector:nomod] Module 'infinite-scroll' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by graingert** [comment]
Have you tried adding:
```js
import infiniteScroll from 'ng-infinite-scroll';
import uiRouter from 'angular-ui-router';
import ngAnimate from 'angular-animate';

import auth from './wherever/auth/is/auth';

const MODULE_NAME = 'MyApp';
export default MODULE_NAME;

angular.module(MODULE_NAME, [auth, infiniteScroll, uiRouter, ngAnimate]);
```

**Comment by harrison0723** [comment]
@graingert I couldn't put down import ___ from ____ syntax as it fails my linter. However, could you show me the es5 equivalent of it?

**Comment by harrison0723** [comment]
Also, for the other dependencies, I seem to be able to do based on
`
<script src="/angular/angular.js"></script>
<script src="/angular-animate/angular-animate.js"></script>
<script src="/angular-ui-router/release/angular-ui-router.js"></script>
`
in my index.html file.

Is there an equivalent url for ngInfiniteScroll?

**Comment by graingert** [comment]
It's best to use a module loader like webpack, browserify, rollup etc

**Comment by graingert** [comment]
https://babeljs.io/repl/#?evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=import%20angular%20from%20'angular'%3B%20import%20infiniteScroll%20from%20'ng-infinite-scroll'%3B%20import%20uiRouter%20from%20'angular-ui-router'%3B%20import%20ngAnimate%20from%20'angular-animate'%3B%20import%20auth%20from%20'.%2Fwherever%2Fauth%2Fis%2Fauth'%3B%20const%20MODULE_NAME%20%3D%20'MyApp'%3B%20export%20default%20MODULE_NAME%3B%20angular.module(MODULE_NAME%2C%20%5Bauth%2C%20infiniteScroll%2C%20uiRouter%2C%20ngAnimate%5D)%3B

**Comment by harrison0723** [comment]
Thanks @graingert 
Turns out the way my app is configured, I simply have to put
`
< script src="/ng-infinite-scroll/build/ng-infinite-scroll.js"></script>
`
(the same structure as in node_modules) in my index.html
