### ISSUE TITLE
Recent change no longer compatible for from end use

### ISSUE THREAD

**Issue by pbrain19** [sroze/ngInfiniteScroll#328]
The recent structure change has made this module unusable in the frontend. Please include dist folder with proper builds. The point of having bower is to be able to use a module out of the box.

**Comment by graingert** [comment]
@pbrain19 please install this module via npm

**Comment by elsewares** [comment]
By taking this off of Bower without notice, you're causing any projects that use it as a dependency in Bower to fail building randomly.

**Comment by graingert** [comment]
The old tags still work. If you want the latest changes however you'll need to use npm. You need npm installed for bower to work

**Comment by elsewares** [comment]
Yes, but it removed the package from Bower for anyone who didn't pin it to 1.3.0 or earlier. This is a breaking change in 1.x.

**Comment by graingert** [comment]
Ah you mean 1.3.1? You should use npm with npm-shrinkwrap

**Comment by elsewares** [comment]
Not to quibble, but breaking the library if installed via Bower isn't a minor change, it's a major one, so 1.4 is called for, at the very least. 

Telling people who are using Bower to go get shrinkwrap isn't a real solution, since they can just clone 1.3.0 and then, say, not use the canonical source anymore because who know how many more breaking changes are coming their way and losing yet more of their workday down the line.

**Comment by pbrain19** [comment]
I just pinned my dependency to 1.3.0. until the maintainer comes to his senses

**Comment by luispeerez** [comment]
Please publish a message when this kind of changes happen, deleting ngInfiniteScroll broke up my frontend dependency configuration on production

**Comment by graingert** [comment]
I'm trying to automate bower builds. That's why 1.3.1 was released

**Comment by elsewares** [comment]
Meanwhile, you broke every build that has ng-infinite-scroll as a dependency and didn't have it pinned to a version.

**Comment by danielcardoso5** [comment]
A production build released on Friday went haywire because of this package, the 1.3 release didn't even mention breaking changes. Why not bower for a frontend dependency? At least keep serving the built module for bower users.

**Comment by graingert** [comment]
@pbrain19 @luispeerez @elsewares @danielcardoso5 Apologies for the down-time of your builds, but bower support was dropped quite a while ago, and you should be aiming to upgrade to npm. However, a bower version is now available at https://github.com/ng-infinite-scroll/ng-infinite-scroll-bower it's auto-built via travis. With thanks to @vikalpj

**Comment by graingert** [comment]
It was as a result of configuring the auto bower builds that this 1.3.1 tag was released.

The semver tags relate to npm versions, not bower. The npm version is tested and verified to work. YMMV on the bower builds.

**Comment by luispeerez** [comment]
Thank you
