### ISSUE TITLE
bower installation broken on version 1.3.1

### ISSUE THREAD

**Issue by navarroaxel** [sroze/ngInfiniteScroll#329]
With this minor patch the build folder is no longer retrieved with the ``bower install ngInfiniteScroll`` command

**Comment by graingert** [comment]
Yeah this is a known issue. I was trying to setup the automated builds.
Please use npm instead

**Comment by stramel** [comment]
@navarroaxel If NPM isn't an option for you. You can point to the last release.

https://github.com/sroze/ngInfiniteScroll/releases

Unfortunately, 1.3.1 didn't have the build files too, So I'm using 1.3.0 release. Modified by `bower.json` to use the following.

`sroze/ngInfiniteScroll#6fbf4b41947f9a3023b4aba0e613231950ccc4a1`

**Comment by graingert** [comment]
@stramel @navarroaxel a bower version is available at https://github.com/ng-infinite-scroll/ng-infinite-scroll-bower It's auto-built via travis.
