### ISSUE TITLE
bower package broken after 1.3.1

### ISSUE THREAD

**Issue by micksi** [sroze/ngInfiniteScroll#334]
After the changes was made to how bower should be installed it is no longer working.
In our bower.json we have, `"ngInfiniteScroll": ~1.3.0 ` in our bower.json.

This is however no longer working as of version 1.3.1 because of a missing bower.json in the package folder or how the js file is referenced now that coffee is no longer used. 
We have reverted back to 1.3.0 and everything is back to normal.

will subsequent release be available in the `ng-infinite-scroll-npm-is-better-than-bower` package?

**Comment by graingert** [comment]
Yes it's going to be available on that bower package
