### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by satyajitdeka** [sroze/ngInfiniteScroll#335]
Hello,

I have followed the steps from https://sroze.github.io/ngInfiniteScroll/
But I run my application, it shows "Uncaught SyntaxError: Unexpected token import" in infinite-scroll.js

Please help me out.

**Comment by graingert** [comment]
Please use the README on https://npmjs.com/package/ng-infinite-scroll

**Comment by albertogiantin** [comment]
Hello,
I have the same problem upgrading from a previous version, so I'm pretty sure that the import of the module is the same in my code...
` angular.module('myApp', [ 'infinite-scroll', ...`
but it doesn't work, can you be more clear on what part of the readme we need to focus?
I've installed the library with bower and i can't find a minified version so i use the extended version o the file infinite-scroll.js

![immagine 1](https://cloud.githubusercontent.com/assets/5612613/19589882/2c6f28d4-976f-11e6-8f6a-96b1f3465256.png)

**Comment by mcfdez** [comment]
Same problem with Angular 1.5.8 and Infinite Scroll 1.3.1

**Comment by graingert** [comment]
Please see the bower instructions:
https://github.com/sroze/ngInfiniteScroll/blob/master/README.md#bower

Or, install via npm.

**Comment by mcfdez** [comment]
Downgrading to 1.3.1 worked well. There is a problem  with version.

**Comment by graingert** [comment]
https://github.com/sroze/ngInfiniteScroll/blob/master/README.md#bower
describes how to use bower for legacy projects. You should prepare to
migrate to npm/webpack, however.
