### ISSUE TITLE
ngInfiniteScroll doesn't work  in  Angular Material ui dailog

### ISSUE THREAD

**Issue by mrpsweet** [sroze/ngInfiniteScroll#337]
It worked in my demo.But when i try it in  Angular Material ui dailog ,the scroll was failure.

**Comment by graingert** [comment]
@mrpsweet if you're using Angular Material you should definitely use Angular Material virtual repeat https://material.angularjs.org/latest/api/directive/mdVirtualRepeat

**Comment by mrpsweet** [comment]
<div infinite-scroll='reddit.nextPage()' infinite-scroll-disabled='reddit.busy' infinite-scroll-distance='1' >

                        <div ng-repeat="item in reddit.items ">

                            <h5 layout="row" >
                                <div>{{item.id}}</div>
                                <div>{{item.appName}}</div>
                                <div>{{item.level}}</div>
                            </h5>
                            <div style='clear: both;'></div>
                        </div>
                        <div ng-show='reddit.busy' style="color: red">Loading data...</div>
                    </div>

        </md-content>

I use this one.Was something wrong?O(∩_∩)O

**Comment by graingert** [comment]
```js
const template = `<md-content>
  <md-virtual-repeat-container>
      <div md-virtual-repeat="i in $ctrl.redditFeed">
            <h5 layout="row" ></h5>
            <div layout="row">
                                <div>{{item.id}}</div>
                                <div>{{item.appName}}</div>
                                <div>{{item.level}}</div>
            </div>
            <div style='clear: both;'></div>
      </div>
  </md-virtual-repeat-container>
</md-content>`;

function getNextRedditPageAfterIndex(index) {
    // implementation left as an exercise for the reader.
}

class RedditFeed() {
  constructor() {
    this.items = [];
  }

  getItemAtIndex(index) {
    if (index > this.items.length) {
      this.fetchMoreItems(index);
      return null;
    }

    return this.items[index];
  }

  getLength() {
    return this.items.length + 5;
  }

  fetchMoreItems(index) {
    getNextRedditPageAfterIndex(index)
      .then(items => this.items.concat(items))
      .then(items => Object.assign(this, { items }));
  }
}

class RedditController() {
  constructor() {
    this.redditFeed = new RedditFeed();
  }
}

export default {
  controller: RedditController,
  template,
}
```

**Comment by mrpsweet** [comment]
Sorry I use Angularjs v1.5.8 and javasript .These code look like ES6.

**Comment by graingert** [comment]
This is ES2016, and mostly pseudo code

**Comment by mrpsweet** [comment]
Thank you anyway(☆_☆)
