### ISSUE TITLE
ngInfiniteScroll bower release license

### ISSUE THREAD

**Issue by ManRueda** [sroze/ngInfiniteScroll#341]
Hi guys,

I'm using this component through bower and i have an issue with the license of it. The code here is under MIT but the bower release is under AGPL. Is this right? Because this component is really useful but ican use if it's AGPL.

Here is the commit of the license change in bower: https://github.com/sroze/ngInfiniteScroll/commit/cedb8cb972976ebcef79900ebf32531c7734d7c0

**Comment by graingert** [comment]
the bower release is under the AGPL, because of its higher cost of maintenance. If you give npm/yarn an honest try I can write you up an exception.

**Comment by ManRueda** [comment]
We have a large set of other components under bower and replace bower with npm/yarn in our current structure it's not possible. Thanks!

**Comment by graingert** [comment]
you can use yarn/npm and bower together, just add an install hook that pulls in bower:

```json
{
    "scripts": {"install": "bower install"}
}
```

then yarn/npm will kick off a bower install just afterwards.

You can then use the contents of `node_modules` as you'd use `bower_components`

**Comment by graingert** [comment]
Also note, that ngInfiniteScroll is only for projects that already use it. New projects should use https://material.angularjs.org/latest/api/directive/mdVirtualRepeat instead.

**Comment by ManRueda** [comment]
Yes but the code that i get from there is the from bower and is under AGPL. If i want to use the code from npm i need to get it from node_modules and that change my deploy strategy. I will check mdVirtualRepeat. Maybe we are on time to use it.

Thanks!

**Comment by graingert** [comment]
@ManRueda which module bundler are you using? RequireJS?

**Comment by ManRueda** [comment]
No, we use usemin to bundle of our files. But the issue is not there, we don't have the node_modules folder in the base folder of all our site so the paths to run the site locally and compile will not match. It's hard to explain because we aren't using the a common path.

**Comment by graingert** [comment]
you can use grunt/gulp to copy directories from node_modules into bower_components

**Comment by ManRueda** [comment]
yes... i can put it in a npm install script to every time that is installed, will be copied.

**Comment by graingert** [comment]
@ManRueda then you can start migrating all your packages to npm. You probably want to use `yarn install --flat` though

**Comment by BinaryMuse** [comment]
I released the original project under the MIT license, and I'm not so sure you can change that just because you want people to stop using Bower:

> The above copyright notice and this permission notice shall be included in **all copies or substantial portions of the Software**.

Furthermore, it's the code that's licensed, not the distribution method. I feel it's a bit dishonest to offer the same code under two different licenses depending on where it lives and how it's installed. I would really appreciate changing the Bower code to use the MIT license, or at least dual-license it so it is still compatible with the MIT license.

**Comment by graingert** [comment]
@BinaryMuse the LICENSE text is now included in the bower build.

**Comment by ManRueda** [comment]
@graingert @BinaryMuse now the license is AGPL-3.0, is sill too restrictive to be used by us.

**Comment by BinaryMuse** [comment]
@graingert I don't want there to be any confusion, so I'm going to be explicit: the code that is being distributed via Bower is licensed under the MIT license. The MIT license explicitly states that you're allowed to distribute the code however you want, but that you **must keep the MIT license**. You do not have a legal right to distribute the Bower code under the AGPL-3.0 license; you must return it to the MIT license.

**Comment by graingert** [comment]
>  must keep the MIT license

This isn't true. 

> including without limitation the rights to use,
copy, modify, merge, publish, distribute, **sublicense**, and/or sell
copies of the Software

I can freely sublicense ngInfiniteScroll however I like. I only have to include the text of the license. It does not need to be legally 'active'

**Comment by graingert** [comment]
Just as someone can take ngInfiniteSroll and include it in a proprietary product, I have taken it and created a derivative work under the AGPL-3.0. (The bower.json + ngInfiniteScroll software).

**Comment by graingert** [comment]
@BinaryMuse  here's blog post about the license https://ttmm.io/tech/why-the-mit-license/

incidentally  the MIT license has been restored
