### ISSUE TITLE
Any plan on deactivating watcher on elements that are out of view?

### ISSUE THREAD

**Issue by shyamal890** [sroze/ngInfiniteScroll#342]
I am facing issue where I have 20 watchers on a row and when more rows come into view the app suddenly becomes very slow.

I wonder if there is a way in which we can deactivate watchers on element which are out of view. Something like ui-scroll. I found and interesting stackoverflow answer which can be utilized for this: http://stackoverflow.com/a/29840248/3955513

**Comment by graingert** [comment]
@shyamal890 no plans for new features. I believe https://material.angularjs.org/latest/api/directive/mdVirtualRepeat takes elements out the dom when they're scrolled past.
