### ISSUE TITLE
Error: module loader

### ISSUE THREAD

**Issue by jbouhier** [sroze/ngInfiniteScroll#344]
Hello dear contributors and maintainers,

With Angular `v1.5.8` and yeoman generator [gulp-angular](https://github.com/Swiip/generator-gulp-angular), there's an error when loading your module ngInfiniteScroll.

With `angular.module('myModule', ['infinite-scroll']);` in my code, neither the ngInfiniteScroll [bower package v1.3.4 ](https://github.com/ng-infinite-scroll/ng-infinite-scroll-bower) nor the ng-infinite-scroll [npm package v1.3.0](https://www.npmjs.com/package/ng-infinite-scroll) can be loaded by Angular. The page just stays blank and the console full of errors.

I had to install the bower package v1.2.2 so that my app can load correctly.
Let me know if you need more infos and if this issue is due to a specific version / tool.

Keep me posted.

**Comment by graingert** [comment]
Can you create an example app on github with the failure?

**Comment by jbouhier** [comment]
You got [it](https://github.com/jbouhier/ngInfiniteScroll_bug).

**Comment by jbouhier** [comment]
I've conducted additional tests.
It appears that the `gulp-angular` generator can't work with npm packages (tested with npm firebase). On the other side bower packages are loaded as they should.

In conclusion, I think I've made a typo or entered an other package name with bower which caused this behaviour: bower ngInfiniteScroll (v1.3.4) works fine.

¯\_(ツ)_/¯

**Comment by graingert** [comment]
@jbouhier looks like gulp-angular is deprecated. Consider webpack/rollup/browserify.
