### ISSUE TITLE
How to get current page number ?

### ISSUE THREAD

**Issue by ntlzz93** [sroze/ngInfiniteScroll#348]
how to determine current page of this pagination page? 

I have a api to pagination such as https://myservices.com/api/getall?page=1&perPage=20
with page is number of this current page
perPage is number of items on page

any idea?

**Comment by graingert** [comment]
Infinite scroll doesn't deal in pages or page numbers.  Try using angular materials virtual repeat

**Comment by lbellows** [comment]
keep a variable in the controller: pageNum=1.  When the load more method is called: pageNum++

**Comment by graingert** [comment]
basically ngInfiniteScroll blindly calls your "get more items" function. That should manage you page state.
