### ISSUE TITLE
This stuff doesn't work.

### ISSUE THREAD

**Issue by azarus** [sroze/ngInfiniteScroll#363]
Hey, your stuff is just not working as expected it's just quite undocumented what each elements does and what the values should be.. for exmaple:
**infinite-scroll-distance ?**
Are they pixel? cm? meter? Or what?

**Comment by graingert** [comment]
I recommend using md-virtual-repeat.

Also, from the documentation:


   - infinite-scroll-distance *(optional)* - {number} - A number
   representing how close the bottom of the element must be to the bottom of
   the browser window before the expression specified by infinite-scroll is
   triggered. Measured in multiples of the window height; for example, if the
   browser window is 1000 pixels tall and infinite-scroll-distance is set
   to 2, the infinite scroll expression will be evaluated when the bottom
   of the element is within 2000 pixels of the bottom of the browser window.
   Defaults to 0 (e.g. the expression will be evaluated when the bottom of
   the element crosses the bottom of the browser window).
