### ISSUE TITLE
GET http://localhost:3000/angular2-infinite-scroll 404 (Not Found)

### ISSUE THREAD

**Issue by shai-benshimol** [sroze/ngInfiniteScroll#365]
Hello,
I dont know what is wrong, after installing infinite scroll and importing into  module
- import { InfiniteScrollModule } from 'angular2-infinite-scroll';
- imports:[ BrowserModule, InfiniteScrollModule ],
 
I'm getting 2 errors:
1) GET http://localhost:3000/angular2-infinite-scroll 404 (Not Found)
2) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/angular2-infinite-scroll

**Comment by wizjack** [comment]
Hi, 
map the bundle in the system.js  configuration.

**Comment by graingert** [comment]
angular2 isn't supported.
