### ISSUE TITLE
How do I get the latest version of ngInfiniteScroll without using bower?

### ISSUE THREAD

**Issue by omgoshjosh** [sroze/ngInfiniteScroll#375]
We recently migrated to yarn, but the NPM/yarn registry says 1.3.0 is the latest release while the ng-infinite-scroll-bower distribution is at 1.3.4 (bower install).

When trying to `yarn install` i am prompted to choose up to 1.3.0 but i want 1.3.4 (which is what our bower version is at). I could use `@bower_components/ngInfiniteScroll` but that just seems wrong.

Is there just no plan to do releases on NPM or is some step missing from publishing the latest version to NPM?

I snooped around the issues and per @graingert found that npm is the preferred method but it's not maintained or released despite there being a few release tags???? I'm pretty confused.

**Comment by omgoshjosh** [comment]
What I've done for now is just use npm to get version 1.3.0 because looking at the commit history from 1.3.0 to 1.3.4, it doesn't even really look like any features or bug fixes have gone in.

As far as I can tell, it looks like it's just fixing tests, readme updates, moving from coffeescript to es6, setting up travis to automatically build/deploy to ng-infinite-scroll-bower, and maybe some other administrative/not-functional changes.

if that's the case, then what i've done seems fine.

**Comment by shovas** [comment]
You can also go to the github project homepage and click Releases near the top and you'll see every version with a ZIP download. The JS file you want is in the build/ folder.

**Comment by neekersMF** [comment]
It would be great for the versions to match on NPM

**Comment by graingert** [comment]
There's no point. There's no code changes between 1.3.0 and 1.3.4 it's only infrastructure changes for bower
