### ISSUE TITLE
To add in FAQ?

### ISSUE THREAD

**Issue by laguiz** [sroze/ngInfiniteScroll#51]
I would like to share my experience using the plugin.

I got a lot of calls calling my pagination while scrolling anywhere in the window.

I had this :

```
<div style="height: 100%" infinite-scroll="pagerFunction()">
   <div ng-repeat="elem in elems">
   </div>
</div>
```

but it was calling a lot of `pagerFunction()`. Similar behaviour to current FAQ `Why is ngInfiniteScroll triggering my expression on every single scroll event?`.

InfiniteScroll seems to use the div offset top and height. As I use `height: 100%` I had to wrap in an additional `div` like this :

```
<div style="height: 100%">
   <div infinite-scroll="pagerFunction()">
      <div ng-repeat="elem in elems">
      </div>
   </div>
</div>
```

Maybe this can help others if put in FAQ.

**Comment by sroze** [comment]
@stefanofornari Could you create a jsfiddle instead, so I could fix it for you ?

**Comment by stefanofornari** [comment]
Hi samuel,
thanks for your reply. I have tried, but I am not very familiar with it and
I could not find a way to make it to work (I mean to create something with
jquery, angular and nginfintescroll), sorry :( However, I worked around my
problem and now works. If you are interested in fixing the issue in
infinitescroll, maybe you can initiate a working jsfiddle and then I will
try to reproduce it?

thanks again,
Stefano

Ste
