### ISSUE TITLE
Add to the documentation that doctype is required

### ISSUE THREAD

**Issue by MattiLehtinen** [sroze/ngInfiniteScroll#90]
Please add to the documentation that `<!DOCTYPE HTML>` is required. Without doctype `$(window).height()` returns same than `$(document).height()` and infinite scroll does not work. Tested with chrome and FF. See http://viralpatel.net/blogs/jquery-window-height-incorrect/

**Comment by pbassut** [comment]
Was this documented? Because I didn't see it and this is what caused #197 for me.
