### ISSUE TITLE
Triggering scroll event when the element becomes shorter

### ISSUE THREAD

**Issue by neoeno** [sroze/ngInfiniteScroll#94]
I have a list with items that can be filtered in or out. I'm using ngInfiniteScroll in this list.

The issue I'm having is that say if I have 1 apple and 9 oranges in my list, and then I click the button to filter out oranges, my list is suddenly only one item long and really needs repopulating. But since ngInfiniteScroll only responds to scroll events, the user has to attempt a scroll before repopulation can happen (and they might not think to do this).

My current solution is to have a function in my controller:

```javascript
var triggerScroll = function(){
    setTimeout(function(){
        $(window).scroll()
    },4)
}
```

(The timeout is there because if I remove the items, then call `$(window).scroll()`, the event is fired before the digest cycle. This means the items haven't been removed from the DOM and so the list is the same height.)

This obviously isn't ideal. 

I'm wondering if there's a case here for ngInfiniteScroll to watch for DOM changes — but unsure due to browser support and increased complexity. The alternative seems to be to be able to do some nicer method of the above — ask ngInfiniteScroll to check after the next digest cycle somehow.

Any ideas? Happy to write a PR for this.

**Comment by arisrais** [comment]
I Have the same problem, any progress on this issue ?

**Comment by baio** [comment]
+1

**Comment by neoeno** [comment]
I might spike this out this week using mutationobservers.

**Comment by neoeno** [comment]
I decided against mutationobservers in favour of @just-boris and @osiloke's suggestions (events).

Pull request https://github.com/sroze/ngInfiniteScroll/pull/167.

I've made a built version on a branch [here](https://github.com/neoeno/ngInfiniteScroll/tree/add_manual_trigger_event_built) if anyone wants to give it a try.
